# The order of the tokens is important, as the first match is used

J_TOKENS = {
    # Ignored patterns
    'COMMENT': r'//.*',
    'SKIP': r'[ \t]+',
    'NEWLINE': r'\n',
    'EOF': r'\0',
    # Literals
    'STRING_LITERAL': r'"[^"]*"',
    'CHAR_LITERAL': r"'.'",
    'FLOAT_LITERAL': r'\d+\.\d+',
    'INT_LITERAL': r'\d+',
    'BOOL_LITERAL': r'yuh|nah',
    'VOID_LITERAL': r'void',
    # Keywords
    'ARRAY': r'int\[\]|float\[\]|bool\[\]|char\[\]|string\[\]',
    'TYPE': r'int|float|bool|char|string|none',
    'ASSIGN': r'be|to',
    'NEW': r'new',
    'PRINT': r'julio says',
    'INPUT': r'julio asks',
    'RETURN': r'julio gets',
    'FUNC_DCL': r'julio wants',
    'IMPORT': r'julio grabs',
    'VAR_DCL': r'make',
    'VAR_CHANGE': r'change',
    'CLASS': r'class',
    'CONSTRUCTOR': r'julio makes',
    'FOR': r'for',
    'IN': r'in',
    'IF': r'is',
    'ELSE': r'otherwise',
    'WHILE': r'till',
    'FOR': r'for',
    'FR': r'fr',
    'THIS': r'me.',
    # Symbols
    'LPAREN': r'\(',
    'RPAREN': r'\)',
    'LBRACE': r'\{',
    'RBRACE': r'\}',
    'LBRACKET': r'\[',
    'RBRACKET': r'\]',
    'COMMA': r',',
    'SEMICOLON': r';',
    'COLON': r':',
    'PERIOD': r'\.',
    'OPERATOR': r'\+|-|\*|/|%',
    'RELATIONAL': r'==|!=|<|>|<=|>=',
    # Identifiers
    'IDENTIFIER': r'[a-zA-Z_][a-zA-Z0-9_]*',
    'MISMATCH': r'.',
}