# The order of the tokens is important, as the first match is used

J_TOKENS = {
    # Ignored patterns
    'COMMENT': r'//.*',
    'TAB': r'[ \t]+',
    'NEWLINE': r'\n',
    'EOF': r'\0',
    # Literals
    'STRING_LITERAL': r'"[^"]*"',
    'CHAR_LITERAL': r"'.'",
    'FLOAT_LITERAL': r'\d+\.\d+',
    'INT_LITERAL': r'\d+',
    'BOOL_LITERAL': r'yuh|nah',
    'VOID_LITERAL': r'None',
    # Keywords
    'TYPE': r'int|float|bool|char|string|none',
    'ASSIGN': r'be|to',
    'NEW': r'new',
    'PRINT': r'julio says',
    'INPUT': r'julio asks',
    'RETURN': r'julio gets',
    'FUNC': r'julio wants',
    'IMPORT': r'julio grabs',
    'FOR': r'julio counts',
    'CONSTRUCTOR': r'julio makes',
    'VAR': r'make',
    'VAR_CHANGE': r'change',
    'WHILE': r'till',
    'IN': r'in',
    'IF': r'is',
    'ELSE': r'otherwise',
    'FR': r'fr',
    'THIS': r'me.',
    'CLASS': r'class',
    # Symbols
    'LPAREN': r'\(',
    'RPAREN': r'\)',
    'LBRACE': r'\{',
    'RBRACE': r'\}',
    'LBRACKET': r'\[',
    'RBRACKET': r'\]',
    'COMMA': r',',
    'SEMICOLON': r';',
    'COLON': r':',
    'PERIOD': r'\.',
    'PLUS': r'\+',
    'MINUS': r'-',
    'TIMES': r'\*',
    'DIVIDE': r'/',
    'MOD': r'%',
    'EXP': r'\*\*',
    'PLUS_EQ': r'\+=',
    'MINUS_EQ': r'-=',
    'TIMES_EQ': r'\*=',
    'DIVIDE_EQ': r'/=',
    'MOD_EQ': r'%=',
    'EXP_EQ': r'\*\*=',
    'RELATIONAL': r'==|!=|<|>|<=|>=',
    # Identifiers
    'ARRAY': r'[a-zA-Z_][a-zA-Z0-9_]*\[\d*\]',
    'IDENTIFIER': r'[a-zA-Z_][a-zA-Z0-9_]*',
    'MISMATCH': r'.',
}